import Menu from "@/componentes/menu/menu";
import "../app/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  )
}


// mi pagina aqui
// https://code-dan.vercel.app/

// paleta de colores "https://paletadecolores.com.mx/paleta/5a867d/436c64/2d524a/163831/001e17/"