import MainCap from "@/app/catalogo/componentes/main/main";
import Titulo from "@/componentes/cursos/titulo/titulo";
import Texto from "@/componentes/cursos/texto/texto";
import Codigo from "@/componentes/cursos/codigo/codigo";
import Web from "@/app/catalogo/componentes/web/web";
import Resumen from "@/componentes/cursos/resumen/resumen";

import logo from "../../../../../../public/logo.jpg";

// css
import "./sticky.css";
import Content from "@/app/catalogo/componentes/content/content";
import Imagen from "@/componentes/cursos/media/imagen/imagen";

export default function PositionStickyCss() {

    return (
        <MainCap>
            <Resumen>
                <Titulo text={`position sticky`}/>
                <Texto texto={`Esto es similar a "position-relative" pero se queda fija en un lugar al igual que fixed.`}/>
                <Codigo lenguaje={"css"} codigo={`position: sticky; /*posisionar en sticky*/`}/>
            </Resumen>

            <Titulo text={`position sticky`}/>
            <Texto texto={`Esto es similar a position: fixed, pero la diferencia es que se comporta más como position: relative. Mientras que fixed se parece a absolute, sticky ocupa un espacio real en el sitio web.`}/>
            <div className="css--positionStickyImagenDeMuestra">
                <img src={logo.src} alt="logo" />
            </div>
            <Codigo lenguaje={"html"} codigo={`<div class="content">
  <div class="pagina">
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.


      <div class="menu">
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
      </div>


      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
        
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
    </p>
  </div>
 </div>`}/>
            <Codigo lenguaje={"css"} codigo={`.menu{
  background-color: blue;
  color: wheat;
  opacity: 0.5;
  width: 100%;
  position: sticky;
  top: 5px;
}`}/>
            <Web>
                <div>
                    <div>
                        <div>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.


                            <div className="css--positionStickyEjemploWeb--ejemplo">
                                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
                            </div>

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.


                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.

                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consecteturrferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                        </div>
                    </div>
                </div>
            </Web>

            <Texto texto={`sticky se usa para hacer que un elemento permanezca fijo en la pantalla después de haber alcanzado una posición específica en el desplazamiento. Para que funcione, siempre debes definir una propiedad como top, left, right o bottom.`}/>

            <Texto texto={`Para entender mejor sticky, fíjate en el logo de la página: se desplaza contigo hasta llegar a una posición específica, donde se mantiene fijo.`}/>
        </MainCap>
    )
}