import MainCap from "@/app/catalogo/componentes/main/main";
import Titulo from "@/componentes/cursos/titulo/titulo";
import Texto from "@/componentes/cursos/texto/texto";
import Codigo from "@/componentes/cursos/codigo/codigo";
import Web from "@/app/catalogo/componentes/web/web";
import Resumen from "@/componentes/cursos/resumen/resumen";
import Enlace from "@/componentes/cursos/enlace/enlace";



import "./fixed.css";

export default function PositionFixedCss() {
    return (
        <MainCap>
            <Resumen>
              <Titulo text={`position fixed`}/>
              <Texto texto={`Esto es similar a position: absolute, solo que la caja se mantiene fija en la pantalla y sigue al contenido. Un ejemplo sería un botón para abrir un resumen.`}/>
              <Codigo lenguaje={"css"} codigo={`position: fixed; /*posisionar en fixed*/`}/>
            </Resumen>
            <Titulo text={`position fixed`}/>
            <Texto texto={`Esto es similar a position: absolute, es decir, no ocupa un espacio real en el sitio web. La diferencia es que el elemento permanece fijo en la pantalla, sin importar el desplazamiento. Se usa comúnmente para menús o publicidades estáticas. Por ejemplo, si sigues bajando, notarás que el menú sigue visible.`}/>
            <Texto texto={`Aquí vamos a simular una página con un menú fijo utilizando la propiedad position: fixed. Esto permitirá que el menú permanezca visible mientras se desplaza el contenido de la página.`}/>
            <Codigo lenguaje={"html"} codigo={`<body>
  <div class="menu">
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
  </div>
  <div class="pagina">
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
    </p>
  </div>
</body>`}/>
            <Codigo lenguaje={"css"} codigo={`.menu{
  background-color: red;
  position: fixed;
  width: 100%;
  color: white;
}`}/>
            <Web>
                <div className="css--positionFixedMenuContent--ejemplo">
                    <div className="css--positionFixedMenu--ejemplo">
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. </p>
                    </div>
                    <div className="css--positionFixedPagina--ejemplo">
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.                
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit quisquam dolorem non similique unde distinctio! A repellat perferendis molestiae rerum similique natus! Quae, numquam commodi? Dolor voluptate doloremque accusamus impedit?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nobis dolores nemo dolor est, veniam perferendis alias neque omnis debitis tempore enim officiis ab! Ab perspiciatis doloribus est eaque quibusdam cupiditate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat nam culpa necessitatibus temporibus nesciunt dolor, nostrum voluptatem consequatur corporis nemo totam consequuntur quod, nobis modi deserunt quasi architecto, facilis ea?
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta vero perferendis dicta quae harum iusto, repudiandae reiciendis illo aspernatur. Dolor architecto cupiditate labore nostrum modi ducimus nisi distinctio Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro quos laudantium maiores. Earum, temporibus laborum maxime illum iusto sequi saepe delectus harum officiis quidem veritatis, debitis laudantium culpa provident alias. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae ipsam vero perspiciatis rerum asperiores reiciendis, hic ea laudantium odit, vel eius tenetur sapiente odio assumenda, perferendis nostrum accusantium. Rem, ab?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas ex molestias nemo error, sed suscipit, magni repellendus et aliquid maxime unde. Excepturi nemo veritatis illo explicabo doloribus, distinctio aut recusandae.
                        </p>
                    </div>
                </div>
            </Web>
            <Texto texto={`Para ver el efecto, es necesario poner la web en pantalla completa en donde dice "Ver en pantalla completa".
Otra forma de notarlo es observando el menú de esta página, donde puedes ver cómo te sigue a medida que bajas.`}/>
            <Texto texto={`Como vemos en el ejemplo, fixed no ocupa espacio en la página, por lo que se superpone sobre el contenido. Esto es fácil de solucionar añadiendo margin-top al contenido u otras soluciones. Puedes experimentar, ya que existen varias formas de ajustarlo.`}/>
            <Enlace link={"/catalogo/css/capitulo_3/positionSticky"} texto={`position sticky`}/>
        </MainCap>
    )
}